### ISSUE TITLE
サンプルデータ作成とテスト

### ISSUE THREAD

**Issue by hiragram** [hiragram/mynextcareer#10]
## 目的
複数のサンプルYAMLファイルを作成し、各ページの表示をテストする。

## 詳細仕様
- 以下の3つのサンプルYAMLファイルを作成:
  1. `data/careers/ios-engineer.yaml` - iOSアプリエンジニア（既存）
  2. `data/careers/frontend-engineer.yaml` - フロントエンドエンジニア:
     ```yaml
     title: "フロントエンドエンジニア"
     last_update: "2025-04-13"
     sections:
       - title: 技術について
         items:
           - key: React
             value: true
             must_have: true
           - key: TypeScript
             value: true
             must_have: true
           - key: テスト駆動開発
             value: true
           - key: マイクロフロントエンド
             value: false
       - title: 組織について
         items:
           - key: フロントエンドエンジニアの人数
             value: 5人以上
             must_have: true
           - key: デザイナーとの協業
             value: true
             must_have: true
       - title: 会社/事業について
         items: 
           - key: リモートワーク
             value: フルリモートもしくは週2以下の出社
             must_have: true
     contact:
       email: "tanaka@example.com"
       github: "tanaka-frontend"
     ```
  3. `data/careers/backend-engineer.yaml` - バックエンドエンジニア:
     ```yaml
     title: "バックエンドエンジニア"
     last_update: "2025-04-13"
     sections:
       - title: 技術について
         items:
           - key: 使用言語
             value: Go, Rust, TypeScript
           - key: マイクロサービス
             value: true
             must_have: true
           - key: クラウド
             value: AWS, GCP
             must_have: true
       - title: 組織について
         items:
           - key: バックエンドエンジニアの人数
             value: 10人以上
           - key: オンコール当番
             value: false
             must_have: true
       - title: 会社/事業について
         items: 
           - key: 事業ドメイン
             value: フィンテック, ヘルスケア
           - key: リモートワーク
             value: フルリモート
             must_have: true
     contact:
       email: "suzuki@example.com"
       twitter: "suzuki_backend"
       github: "suzuki-dev"
     ```
- 各ページの表示をテスト:
  - トップページでのリスト表示
  - 各詳細ページの表示
  - レスポンシブデザインの確認

## ユニットテスト要件
- 必ずユニットテストを書くこと
- テスト内容:
  - サンプルデータが正しく読み込まれることを確認
  - トップページに全てのサンプルが表示されることを確認
  - 各詳細ページが正しく表示されることを確認

## 受け入れ基準
- すべてのサンプルデータが正しく作成され、読み込まれる
- トップページと詳細ページが正しく表示される
- すべてのユニットテストが通過する
