### ISSUE TITLE
ディレクトリ構造の整備

### ISSUE THREAD

**Issue by hiragram** [hiragram/mynextcareer#2]
## 目的
プロジェクトの基本的なディレクトリ構造を整備し、開発の土台を作る。

## 詳細仕様
- 以下のディレクトリ構造を作成:
  ```
  /data/
    /careers/      # YAMLファイルを格納
  /app/
    /careers/
      /[id]/       # 詳細ページ用
        page.tsx
  /components/     # 共通コンポーネント
    /ui/           # UIコンポーネント
    /layout/       # レイアウトコンポーネント
  /lib/            # ユーティリティ関数
    /yaml/         # YAML関連の処理
  /types/          # 型定義ファイル
  /tests/          # テストファイル
  ```
- サンプルYAMLファイルを1つ作成（`data/careers/ios-engineer.yaml`）:
  ```yaml
  # 基本情報
  title: "iOSアプリエンジニア"
  last_update: "2025-04-13"
  sections:
    - title: 技術について
      items:
        - key: Objective-Cがない
          value: true
          must_have: true
        - key: CI環境
          value: Xcode Cloud, Bitrise, GitHub Actions
          must_have: true
        - key: 高スペックな開発用iPhoneが貸与される
          value: true
        - key: Flutter
          value: false
          must_have: true
    - title: 組織について
      items:
        - key: iOSアプリエンジニアの人数
          value: 3人以上
          must_have: true
        - key: CTO, VPoEもしくはそれに準ずる人がいる
          value: true
          must_have: true
    - title: 会社/事業について
      items: 
        - key: BtoCのサービスであること
          value: true
        - key: 新規事業に挑戦できること
          value: true
        - key: リモートワーク
          value: フルリモートもしくは週1以下の出社
  # 連絡先（オプション）
  contact:
    email: "yamada@example.com"
  ```

## ユニットテスト要件
- 必ずユニットテストを書くこと
- テスト内容:
  - ディレクトリ構造が正しく作成されていることを確認
  - サンプルYAMLファイルが正しく配置され、読み込めることを確認

## 受け入れ基準
- すべてのディレクトリが正しく作成されている
- サンプルYAMLファイルが正しく配置され、読み込める
- すべてのユニットテストが通過する
